package per.itachi.test.music;

public class TagID3V22Constants {
	
	public final static String STR_FRAME_ID_BUF="BUF";
	public final static String STR_FRAME_ID_CNT="CNT";
	public final static String STR_FRAME_ID_COM="COM";
	public final static String STR_FRAME_ID_CRA="CRA";
	public final static String STR_FRAME_ID_CRM="CRM";
	public final static String STR_FRAME_ID_ETC="ETC";
	public final static String STR_FRAME_ID_EQU="EQU";
	public final static String STR_FRAME_ID_GEO="GEO";
	public final static String STR_FRAME_ID_IPL="IPL";
	public final static String STR_FRAME_ID_LNK="LNK";
	public final static String STR_FRAME_ID_MCI="MCI";
	public final static String STR_FRAME_ID_MLL="MLL";
	public final static String STR_FRAME_ID_PIC="PIC";
	public final static String STR_FRAME_ID_POP="POP";
	public final static String STR_FRAME_ID_REV="REV";
	public final static String STR_FRAME_ID_RVA="RVA";
	public final static String STR_FRAME_ID_SLT="SLT";
	public final static String STR_FRAME_ID_STC="STC";
	public final static String STR_FRAME_ID_TAL="TAL";
	public final static String STR_FRAME_ID_TBP="TBP";
	public final static String STR_FRAME_ID_TCM="TCM";
	public final static String STR_FRAME_ID_TCO="TCO";
	public final static String STR_FRAME_ID_TCR="TCR";
	public final static String STR_FRAME_ID_TDA="TDA";
	public final static String STR_FRAME_ID_TDY="TDY";
	public final static String STR_FRAME_ID_TEN="TEN";
	public final static String STR_FRAME_ID_TFT="TFT";
	public final static String STR_FRAME_ID_TIM="TIM";
	public final static String STR_FRAME_ID_TKE="TKE";
	public final static String STR_FRAME_ID_TLA="TLA";
	public final static String STR_FRAME_ID_TLE="TLE";
	public final static String STR_FRAME_ID_TMT="TMT";
	public final static String STR_FRAME_ID_TOA="TOA";
	public final static String STR_FRAME_ID_TOF="TOF";
	public final static String STR_FRAME_ID_TOL="TOL";
	public final static String STR_FRAME_ID_TOR="TOR";
	public final static String STR_FRAME_ID_TOT="TOT";
	public final static String STR_FRAME_ID_TP1="TP1";
	public final static String STR_FRAME_ID_TP2="TP2";
	public final static String STR_FRAME_ID_TP3="TP3";
	public final static String STR_FRAME_ID_TP4="TP4";
	public final static String STR_FRAME_ID_TPA="TPA";
	public final static String STR_FRAME_ID_TPB="TPB";
	public final static String STR_FRAME_ID_TRC="TRC";
	public final static String STR_FRAME_ID_TRD="TRD";
	public final static String STR_FRAME_ID_TRK="TRK";
	public final static String STR_FRAME_ID_TSI="TSI";
	public final static String STR_FRAME_ID_TSS="TSS";
	public final static String STR_FRAME_ID_TT1="TT1";
	public final static String STR_FRAME_ID_TT2="TT2";
	public final static String STR_FRAME_ID_TT3="TT3";
	public final static String STR_FRAME_ID_TXT="TXT";
	public final static String STR_FRAME_ID_TXX="TXX";
	public final static String STR_FRAME_ID_TYE="TYE";
	public final static String STR_FRAME_ID_UFI="UFI";
	public final static String STR_FRAME_ID_ULT="ULT";
	public final static String STR_FRAME_ID_WAF="WAF";
	public final static String STR_FRAME_ID_WAR="WAR";
	public final static String STR_FRAME_ID_WAS="WAS";
	public final static String STR_FRAME_ID_WCM="WCM";
	public final static String STR_FRAME_ID_WCP="WCP";
	public final static String STR_FRAME_ID_WPB="WPB";
	public final static String STR_FRAME_ID_WXX="WXX";

	public static byte[] BYTES_FRAME_ID_BUF;
	public static byte[] BYTES_FRAME_ID_CNT;
	public static byte[] BYTES_FRAME_ID_COM;
	public static byte[] BYTES_FRAME_ID_CRA;
	public static byte[] BYTES_FRAME_ID_CRM;
	public static byte[] BYTES_FRAME_ID_ETC;
	public static byte[] BYTES_FRAME_ID_EQU;
	public static byte[] BYTES_FRAME_ID_GEO;
	public static byte[] BYTES_FRAME_ID_IPL;
	public static byte[] BYTES_FRAME_ID_LNK;
	public static byte[] BYTES_FRAME_ID_MCI;
	public static byte[] BYTES_FRAME_ID_MLL;
	public static byte[] BYTES_FRAME_ID_PIC;
	public static byte[] BYTES_FRAME_ID_POP;
	public static byte[] BYTES_FRAME_ID_REV;
	public static byte[] BYTES_FRAME_ID_RVA;
	public static byte[] BYTES_FRAME_ID_SLT;
	public static byte[] BYTES_FRAME_ID_STC;
	public static byte[] BYTES_FRAME_ID_TAL;
	public static byte[] BYTES_FRAME_ID_TBP;
	public static byte[] BYTES_FRAME_ID_TCM;
	public static byte[] BYTES_FRAME_ID_TCO;
	public static byte[] BYTES_FRAME_ID_TCR;
	public static byte[] BYTES_FRAME_ID_TDA;
	public static byte[] BYTES_FRAME_ID_TDY;
	public static byte[] BYTES_FRAME_ID_TEN;
	public static byte[] BYTES_FRAME_ID_TFT;
	public static byte[] BYTES_FRAME_ID_TIM;
	public static byte[] BYTES_FRAME_ID_TKE;
	public static byte[] BYTES_FRAME_ID_TLA;
	public static byte[] BYTES_FRAME_ID_TLE;
	public static byte[] BYTES_FRAME_ID_TMT;
	public static byte[] BYTES_FRAME_ID_TOA;
	public static byte[] BYTES_FRAME_ID_TOF;
	public static byte[] BYTES_FRAME_ID_TOL;
	public static byte[] BYTES_FRAME_ID_TOR;
	public static byte[] BYTES_FRAME_ID_TOT;
	public static byte[] BYTES_FRAME_ID_TP1;
	public static byte[] BYTES_FRAME_ID_TP2;
	public static byte[] BYTES_FRAME_ID_TP3;
	public static byte[] BYTES_FRAME_ID_TP4;
	public static byte[] BYTES_FRAME_ID_TPA;
	public static byte[] BYTES_FRAME_ID_TPB;
	public static byte[] BYTES_FRAME_ID_TRC;
	public static byte[] BYTES_FRAME_ID_TRD;
	public static byte[] BYTES_FRAME_ID_TRK;
	public static byte[] BYTES_FRAME_ID_TSI;
	public static byte[] BYTES_FRAME_ID_TSS;
	public static byte[] BYTES_FRAME_ID_TT1;
	public static byte[] BYTES_FRAME_ID_TT2;
	public static byte[] BYTES_FRAME_ID_TT3;
	public static byte[] BYTES_FRAME_ID_TXT;
	public static byte[] BYTES_FRAME_ID_TXX;
	public static byte[] BYTES_FRAME_ID_TYE;
	public static byte[] BYTES_FRAME_ID_UFI;
	public static byte[] BYTES_FRAME_ID_ULT;
	public static byte[] BYTES_FRAME_ID_WAF;
	public static byte[] BYTES_FRAME_ID_WAR;
	public static byte[] BYTES_FRAME_ID_WAS;
	public static byte[] BYTES_FRAME_ID_WCM;
	public static byte[] BYTES_FRAME_ID_WCP;
	public static byte[] BYTES_FRAME_ID_WPB;
	public static byte[] BYTES_FRAME_ID_WXX;
	
	static{
		try {
			BYTES_FRAME_ID_BUF = STR_FRAME_ID_BUF.getBytes("utf-8");
			BYTES_FRAME_ID_CNT = STR_FRAME_ID_CNT.getBytes("utf-8");
			BYTES_FRAME_ID_COM = STR_FRAME_ID_COM.getBytes("utf-8");
			BYTES_FRAME_ID_CRA = STR_FRAME_ID_CRA.getBytes("utf-8");
			BYTES_FRAME_ID_CRM = STR_FRAME_ID_CRM.getBytes("utf-8");
			BYTES_FRAME_ID_ETC = STR_FRAME_ID_ETC.getBytes("utf-8");
			BYTES_FRAME_ID_EQU = STR_FRAME_ID_EQU.getBytes("utf-8");
			BYTES_FRAME_ID_GEO = STR_FRAME_ID_GEO.getBytes("utf-8");
			BYTES_FRAME_ID_IPL = STR_FRAME_ID_IPL.getBytes("utf-8");
			BYTES_FRAME_ID_LNK = STR_FRAME_ID_LNK.getBytes("utf-8");
			BYTES_FRAME_ID_MCI = STR_FRAME_ID_MCI.getBytes("utf-8");
			BYTES_FRAME_ID_MLL = STR_FRAME_ID_MLL.getBytes("utf-8");
			BYTES_FRAME_ID_PIC = STR_FRAME_ID_PIC.getBytes("utf-8");
			BYTES_FRAME_ID_POP = STR_FRAME_ID_POP.getBytes("utf-8");
			BYTES_FRAME_ID_REV = STR_FRAME_ID_REV.getBytes("utf-8");
			BYTES_FRAME_ID_RVA = STR_FRAME_ID_RVA.getBytes("utf-8");
			BYTES_FRAME_ID_SLT = STR_FRAME_ID_SLT.getBytes("utf-8");
			BYTES_FRAME_ID_STC = STR_FRAME_ID_STC.getBytes("utf-8");
			BYTES_FRAME_ID_TAL = STR_FRAME_ID_TAL.getBytes("utf-8");
			BYTES_FRAME_ID_TBP = STR_FRAME_ID_TBP.getBytes("utf-8");
			BYTES_FRAME_ID_TCM = STR_FRAME_ID_TCM.getBytes("utf-8");
			BYTES_FRAME_ID_TCO = STR_FRAME_ID_TCO.getBytes("utf-8");
			BYTES_FRAME_ID_TCR = STR_FRAME_ID_TCR.getBytes("utf-8");
			BYTES_FRAME_ID_TDA = STR_FRAME_ID_TDA.getBytes("utf-8");
			BYTES_FRAME_ID_TDY = STR_FRAME_ID_TDY.getBytes("utf-8");
			BYTES_FRAME_ID_TEN = STR_FRAME_ID_TEN.getBytes("utf-8");
			BYTES_FRAME_ID_TFT = STR_FRAME_ID_TFT.getBytes("utf-8");
			BYTES_FRAME_ID_TIM = STR_FRAME_ID_TIM.getBytes("utf-8");
			BYTES_FRAME_ID_TKE = STR_FRAME_ID_TKE.getBytes("utf-8");
			BYTES_FRAME_ID_TLA = STR_FRAME_ID_TLA.getBytes("utf-8");
			BYTES_FRAME_ID_TLE = STR_FRAME_ID_TLE.getBytes("utf-8");
			BYTES_FRAME_ID_TMT = STR_FRAME_ID_TMT.getBytes("utf-8");
			BYTES_FRAME_ID_TOA = STR_FRAME_ID_TOA.getBytes("utf-8");
			BYTES_FRAME_ID_TOF = STR_FRAME_ID_TOF.getBytes("utf-8");
			BYTES_FRAME_ID_TOL = STR_FRAME_ID_TOL.getBytes("utf-8");
			BYTES_FRAME_ID_TOR = STR_FRAME_ID_TOR.getBytes("utf-8");
			BYTES_FRAME_ID_TOT = STR_FRAME_ID_TOT.getBytes("utf-8");
			BYTES_FRAME_ID_TP1 = STR_FRAME_ID_TP1.getBytes("utf-8");
			BYTES_FRAME_ID_TP2 = STR_FRAME_ID_TP2.getBytes("utf-8");
			BYTES_FRAME_ID_TP3 = STR_FRAME_ID_TP3.getBytes("utf-8");
			BYTES_FRAME_ID_TP4 = STR_FRAME_ID_TP4.getBytes("utf-8");
			BYTES_FRAME_ID_TPA = STR_FRAME_ID_TPA.getBytes("utf-8");
			BYTES_FRAME_ID_TPB = STR_FRAME_ID_TPB.getBytes("utf-8");
			BYTES_FRAME_ID_TRC = STR_FRAME_ID_TRC.getBytes("utf-8");
			BYTES_FRAME_ID_TRD = STR_FRAME_ID_TRD.getBytes("utf-8");
			BYTES_FRAME_ID_TRK = STR_FRAME_ID_TRK.getBytes("utf-8");
			BYTES_FRAME_ID_TSI = STR_FRAME_ID_TSI.getBytes("utf-8");
			BYTES_FRAME_ID_TSS = STR_FRAME_ID_TSS.getBytes("utf-8");
			BYTES_FRAME_ID_TT1 = STR_FRAME_ID_TT1.getBytes("utf-8");
			BYTES_FRAME_ID_TT2 = STR_FRAME_ID_TT2.getBytes("utf-8");
			BYTES_FRAME_ID_TT3 = STR_FRAME_ID_TT3.getBytes("utf-8");
			BYTES_FRAME_ID_TXT = STR_FRAME_ID_TXT.getBytes("utf-8");
			BYTES_FRAME_ID_TXX = STR_FRAME_ID_TXX.getBytes("utf-8");
			BYTES_FRAME_ID_TYE = STR_FRAME_ID_TYE.getBytes("utf-8");
			BYTES_FRAME_ID_UFI = STR_FRAME_ID_UFI.getBytes("utf-8");
			BYTES_FRAME_ID_ULT = STR_FRAME_ID_ULT.getBytes("utf-8");
			BYTES_FRAME_ID_WAF = STR_FRAME_ID_WAF.getBytes("utf-8");
			BYTES_FRAME_ID_WAR = STR_FRAME_ID_WAR.getBytes("utf-8");
			BYTES_FRAME_ID_WAS = STR_FRAME_ID_WAS.getBytes("utf-8");
			BYTES_FRAME_ID_WCM = STR_FRAME_ID_WCM.getBytes("utf-8");
			BYTES_FRAME_ID_WCP = STR_FRAME_ID_WCP.getBytes("utf-8");
			BYTES_FRAME_ID_WPB = STR_FRAME_ID_WPB.getBytes("utf-8");
			BYTES_FRAME_ID_WXX = STR_FRAME_ID_WXX.getBytes("utf-8");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}