package per.itachi.test.music;

public class TagID3V23Constants {
	
	public final static String STR_FRAME_ID_AENC="AENC";
	public final static String STR_FRAME_ID_APIC="APIC";
	public final static String STR_FRAME_ID_COMM="COMM";
	public final static String STR_FRAME_ID_COMR="COMR";
	public final static String STR_FRAME_ID_ENCR="ENCR";
	public final static String STR_FRAME_ID_EQUA="EQUA";
	public final static String STR_FRAME_ID_ETCO="ETCO";
	public final static String STR_FRAME_ID_GEOB="GEOB";
	public final static String STR_FRAME_ID_GRID="GRID";
	public final static String STR_FRAME_ID_IPLS="IPLS";
	public final static String STR_FRAME_ID_LINK="LINK";
	public final static String STR_FRAME_ID_MCDI="MCDI";
	public final static String STR_FRAME_ID_MLLT="MLLT";
	public final static String STR_FRAME_ID_OWNE="OWNE";
	public final static String STR_FRAME_ID_PRIV="PRIV";
	public final static String STR_FRAME_ID_PCNT="PCNT";
	public final static String STR_FRAME_ID_POPM="POPM";
	public final static String STR_FRAME_ID_POSS="POSS";
	public final static String STR_FRAME_ID_RBUF="RBUF";
	public final static String STR_FRAME_ID_RVAD="RVAD";
	public final static String STR_FRAME_ID_RVRB="RVRB";
	public final static String STR_FRAME_ID_SYLT="SYLT";
	public final static String STR_FRAME_ID_SYTC="SYTC";
	public final static String STR_FRAME_ID_TALB="TALB";
	public final static String STR_FRAME_ID_TBPM="TBPM";
	public final static String STR_FRAME_ID_TCOM="TCOM";
	public final static String STR_FRAME_ID_TCON="TCON";
	public final static String STR_FRAME_ID_TCOP="TCOP";
	public final static String STR_FRAME_ID_TDAT="TDAT";
	public final static String STR_FRAME_ID_TDLY="TDLY";
	public final static String STR_FRAME_ID_TENC="TENC";
	public final static String STR_FRAME_ID_TEXT="TEXT";
	public final static String STR_FRAME_ID_TFLT="TFLT";
	public final static String STR_FRAME_ID_TIME="TIME";
	public final static String STR_FRAME_ID_TIT1="TIT1";
	public final static String STR_FRAME_ID_TIT2="TIT2";
	public final static String STR_FRAME_ID_TIT3="TIT3";
	public final static String STR_FRAME_ID_TKEY="TKEY";
	public final static String STR_FRAME_ID_TLAN="TLAN";
	public final static String STR_FRAME_ID_TLEN="TLEN";
	public final static String STR_FRAME_ID_TMED="TMED";
	public final static String STR_FRAME_ID_TOAL="TOAL";
	public final static String STR_FRAME_ID_TOFN="TOFN";
	public final static String STR_FRAME_ID_TOLY="TOLY";
	public final static String STR_FRAME_ID_TOPE="TOPE";
	public final static String STR_FRAME_ID_TORY="TORY";
	public final static String STR_FRAME_ID_TOWN="TOWN";
	public final static String STR_FRAME_ID_TPE1="TPE1";
	public final static String STR_FRAME_ID_TPE2="TPE2";
	public final static String STR_FRAME_ID_TPE3="TPE3";
	public final static String STR_FRAME_ID_TPE4="TPE4";
	public final static String STR_FRAME_ID_TPOS="TPOS";
	public final static String STR_FRAME_ID_TPUB="TPUB";
	public final static String STR_FRAME_ID_TRCK="TRCK";
	public final static String STR_FRAME_ID_TRDA="TRDA";
	public final static String STR_FRAME_ID_TRSN="TRSN";
	public final static String STR_FRAME_ID_TRSO="TRSO";
	public final static String STR_FRAME_ID_TSIZ="TSIZ";
	public final static String STR_FRAME_ID_TSRC="TSRC";
	public final static String STR_FRAME_ID_TSSE="TSSE";
	public final static String STR_FRAME_ID_TYER="TYER";
	public final static String STR_FRAME_ID_TXXX="TXXX";
	public final static String STR_FRAME_ID_UFID="UFID";
	public final static String STR_FRAME_ID_USER="USER";
	public final static String STR_FRAME_ID_USLT="USLT";
	public final static String STR_FRAME_ID_WCOM="WCOM";
	public final static String STR_FRAME_ID_WCOP="WCOP";
	public final static String STR_FRAME_ID_WOAF="WOAF";
	public final static String STR_FRAME_ID_WOAR="WOAR";
	public final static String STR_FRAME_ID_WOAS="WOAS";
	public final static String STR_FRAME_ID_WORS="WORS";
	public final static String STR_FRAME_ID_WPAY="WPAY";
	public final static String STR_FRAME_ID_WPUB="WPUB";
	public final static String STR_FRAME_ID_WXXX="WXXX";
	
	public static byte[] BYTES_FRAME_ID_AENC;
	public static byte[] BYTES_FRAME_ID_APIC;
	public static byte[] BYTES_FRAME_ID_COMM;
	public static byte[] BYTES_FRAME_ID_COMR;
	public static byte[] BYTES_FRAME_ID_ENCR;
	public static byte[] BYTES_FRAME_ID_EQUA;
	public static byte[] BYTES_FRAME_ID_ETCO;
	public static byte[] BYTES_FRAME_ID_GEOB;
	public static byte[] BYTES_FRAME_ID_GRID;
	public static byte[] BYTES_FRAME_ID_IPLS;
	public static byte[] BYTES_FRAME_ID_LINK;
	public static byte[] BYTES_FRAME_ID_MCDI;
	public static byte[] BYTES_FRAME_ID_MLLT;
	public static byte[] BYTES_FRAME_ID_OWNE;
	public static byte[] BYTES_FRAME_ID_PRIV;
	public static byte[] BYTES_FRAME_ID_PCNT;
	public static byte[] BYTES_FRAME_ID_POPM;
	public static byte[] BYTES_FRAME_ID_POSS;
	public static byte[] BYTES_FRAME_ID_RBUF;
	public static byte[] BYTES_FRAME_ID_RVAD;
	public static byte[] BYTES_FRAME_ID_RVRB;
	public static byte[] BYTES_FRAME_ID_SYLT;
	public static byte[] BYTES_FRAME_ID_SYTC;
	public static byte[] BYTES_FRAME_ID_TALB;
	public static byte[] BYTES_FRAME_ID_TBPM;
	public static byte[] BYTES_FRAME_ID_TCOM;
	public static byte[] BYTES_FRAME_ID_TCON;
	public static byte[] BYTES_FRAME_ID_TCOP;
	public static byte[] BYTES_FRAME_ID_TDAT;
	public static byte[] BYTES_FRAME_ID_TDLY;
	public static byte[] BYTES_FRAME_ID_TENC;
	public static byte[] BYTES_FRAME_ID_TEXT;
	public static byte[] BYTES_FRAME_ID_TFLT;
	public static byte[] BYTES_FRAME_ID_TIME;
	public static byte[] BYTES_FRAME_ID_TIT1;
	public static byte[] BYTES_FRAME_ID_TIT2;
	public static byte[] BYTES_FRAME_ID_TIT3;
	public static byte[] BYTES_FRAME_ID_TKEY;
	public static byte[] BYTES_FRAME_ID_TLAN;
	public static byte[] BYTES_FRAME_ID_TLEN;
	public static byte[] BYTES_FRAME_ID_TMED;
	public static byte[] BYTES_FRAME_ID_TOAL;
	public static byte[] BYTES_FRAME_ID_TOFN;
	public static byte[] BYTES_FRAME_ID_TOLY;
	public static byte[] BYTES_FRAME_ID_TOPE;
	public static byte[] BYTES_FRAME_ID_TORY;
	public static byte[] BYTES_FRAME_ID_TOWN;
	public static byte[] BYTES_FRAME_ID_TPE1;
	public static byte[] BYTES_FRAME_ID_TPE2;
	public static byte[] BYTES_FRAME_ID_TPE3;
	public static byte[] BYTES_FRAME_ID_TPE4;
	public static byte[] BYTES_FRAME_ID_TPOS;
	public static byte[] BYTES_FRAME_ID_TPUB;
	public static byte[] BYTES_FRAME_ID_TRCK;
	public static byte[] BYTES_FRAME_ID_TRDA;
	public static byte[] BYTES_FRAME_ID_TRSN;
	public static byte[] BYTES_FRAME_ID_TRSO;
	public static byte[] BYTES_FRAME_ID_TSIZ;
	public static byte[] BYTES_FRAME_ID_TSRC;
	public static byte[] BYTES_FRAME_ID_TSSE;
	public static byte[] BYTES_FRAME_ID_TYER;
	public static byte[] BYTES_FRAME_ID_TXXX;
	public static byte[] BYTES_FRAME_ID_UFID;
	public static byte[] BYTES_FRAME_ID_USER;
	public static byte[] BYTES_FRAME_ID_USLT;
	public static byte[] BYTES_FRAME_ID_WCOM;
	public static byte[] BYTES_FRAME_ID_WCOP;
	public static byte[] BYTES_FRAME_ID_WOAF;
	public static byte[] BYTES_FRAME_ID_WOAR;
	public static byte[] BYTES_FRAME_ID_WOAS;
	public static byte[] BYTES_FRAME_ID_WORS;
	public static byte[] BYTES_FRAME_ID_WPAY;
	public static byte[] BYTES_FRAME_ID_WPUB;
	public static byte[] BYTES_FRAME_ID_WXXX;
	
	static{
		try {
			BYTES_FRAME_ID_AENC=STR_FRAME_ID_AENC.getBytes("utf-8");
			BYTES_FRAME_ID_APIC=STR_FRAME_ID_APIC.getBytes("utf-8");
			BYTES_FRAME_ID_COMM=STR_FRAME_ID_COMM.getBytes("utf-8");
			BYTES_FRAME_ID_COMR=STR_FRAME_ID_COMR.getBytes("utf-8");
			BYTES_FRAME_ID_ENCR=STR_FRAME_ID_ENCR.getBytes("utf-8");
			BYTES_FRAME_ID_EQUA=STR_FRAME_ID_EQUA.getBytes("utf-8");
			BYTES_FRAME_ID_ETCO=STR_FRAME_ID_ETCO.getBytes("utf-8");
			BYTES_FRAME_ID_GEOB=STR_FRAME_ID_GEOB.getBytes("utf-8");
			BYTES_FRAME_ID_GRID=STR_FRAME_ID_GRID.getBytes("utf-8");
			BYTES_FRAME_ID_IPLS=STR_FRAME_ID_IPLS.getBytes("utf-8");
			BYTES_FRAME_ID_LINK=STR_FRAME_ID_LINK.getBytes("utf-8");
			BYTES_FRAME_ID_MCDI=STR_FRAME_ID_MCDI.getBytes("utf-8");
			BYTES_FRAME_ID_MLLT=STR_FRAME_ID_MLLT.getBytes("utf-8");
			BYTES_FRAME_ID_OWNE=STR_FRAME_ID_OWNE.getBytes("utf-8");
			BYTES_FRAME_ID_PRIV=STR_FRAME_ID_PRIV.getBytes("utf-8");
			BYTES_FRAME_ID_PCNT=STR_FRAME_ID_PCNT.getBytes("utf-8");
			BYTES_FRAME_ID_POPM=STR_FRAME_ID_POPM.getBytes("utf-8");
			BYTES_FRAME_ID_POSS=STR_FRAME_ID_POSS.getBytes("utf-8");
			BYTES_FRAME_ID_RBUF=STR_FRAME_ID_RBUF.getBytes("utf-8");
			BYTES_FRAME_ID_RVAD=STR_FRAME_ID_RVAD.getBytes("utf-8");
			BYTES_FRAME_ID_RVRB=STR_FRAME_ID_RVRB.getBytes("utf-8");
			BYTES_FRAME_ID_SYLT=STR_FRAME_ID_SYLT.getBytes("utf-8");
			BYTES_FRAME_ID_SYTC=STR_FRAME_ID_SYTC.getBytes("utf-8");
			BYTES_FRAME_ID_TALB=STR_FRAME_ID_TALB.getBytes("utf-8");
			BYTES_FRAME_ID_TBPM=STR_FRAME_ID_TBPM.getBytes("utf-8");
			BYTES_FRAME_ID_TCOM=STR_FRAME_ID_TCOM.getBytes("utf-8");
			BYTES_FRAME_ID_TCON=STR_FRAME_ID_TCON.getBytes("utf-8");
			BYTES_FRAME_ID_TCOP=STR_FRAME_ID_TCOP.getBytes("utf-8");
			BYTES_FRAME_ID_TDAT=STR_FRAME_ID_TDAT.getBytes("utf-8");
			BYTES_FRAME_ID_TDLY=STR_FRAME_ID_TDLY.getBytes("utf-8");
			BYTES_FRAME_ID_TENC=STR_FRAME_ID_TENC.getBytes("utf-8");
			BYTES_FRAME_ID_TEXT=STR_FRAME_ID_TEXT.getBytes("utf-8");
			BYTES_FRAME_ID_TFLT=STR_FRAME_ID_TFLT.getBytes("utf-8");
			BYTES_FRAME_ID_TIME=STR_FRAME_ID_TIME.getBytes("utf-8");
			BYTES_FRAME_ID_TIT1=STR_FRAME_ID_TIT1.getBytes("utf-8");
			BYTES_FRAME_ID_TIT2=STR_FRAME_ID_TIT2.getBytes("utf-8");
			BYTES_FRAME_ID_TIT3=STR_FRAME_ID_TIT3.getBytes("utf-8");
			BYTES_FRAME_ID_TKEY=STR_FRAME_ID_TKEY.getBytes("utf-8");
			BYTES_FRAME_ID_TLAN=STR_FRAME_ID_TLAN.getBytes("utf-8");
			BYTES_FRAME_ID_TLEN=STR_FRAME_ID_TLEN.getBytes("utf-8");
			BYTES_FRAME_ID_TMED=STR_FRAME_ID_TMED.getBytes("utf-8");
			BYTES_FRAME_ID_TOAL=STR_FRAME_ID_TOAL.getBytes("utf-8");
			BYTES_FRAME_ID_TOFN=STR_FRAME_ID_TOFN.getBytes("utf-8");
			BYTES_FRAME_ID_TOLY=STR_FRAME_ID_TOLY.getBytes("utf-8");
			BYTES_FRAME_ID_TOPE=STR_FRAME_ID_TOPE.getBytes("utf-8");
			BYTES_FRAME_ID_TORY=STR_FRAME_ID_TORY.getBytes("utf-8");
			BYTES_FRAME_ID_TOWN=STR_FRAME_ID_TOWN.getBytes("utf-8");
			BYTES_FRAME_ID_TPE1=STR_FRAME_ID_TPE1.getBytes("utf-8");
			BYTES_FRAME_ID_TPE2=STR_FRAME_ID_TPE2.getBytes("utf-8");
			BYTES_FRAME_ID_TPE3=STR_FRAME_ID_TPE3.getBytes("utf-8");
			BYTES_FRAME_ID_TPE4=STR_FRAME_ID_TPE4.getBytes("utf-8");
			BYTES_FRAME_ID_TPOS=STR_FRAME_ID_TPOS.getBytes("utf-8");
			BYTES_FRAME_ID_TPUB=STR_FRAME_ID_TPUB.getBytes("utf-8");
			BYTES_FRAME_ID_TRCK=STR_FRAME_ID_TRCK.getBytes("utf-8");
			BYTES_FRAME_ID_TRDA=STR_FRAME_ID_TRDA.getBytes("utf-8");
			BYTES_FRAME_ID_TRSN=STR_FRAME_ID_TRSN.getBytes("utf-8");
			BYTES_FRAME_ID_TRSO=STR_FRAME_ID_TRSO.getBytes("utf-8");
			BYTES_FRAME_ID_TSIZ=STR_FRAME_ID_TSIZ.getBytes("utf-8");
			BYTES_FRAME_ID_TSRC=STR_FRAME_ID_TSRC.getBytes("utf-8");
			BYTES_FRAME_ID_TSSE=STR_FRAME_ID_TSSE.getBytes("utf-8");
			BYTES_FRAME_ID_TYER=STR_FRAME_ID_TYER.getBytes("utf-8");
			BYTES_FRAME_ID_TXXX=STR_FRAME_ID_TXXX.getBytes("utf-8");
			BYTES_FRAME_ID_UFID=STR_FRAME_ID_UFID.getBytes("utf-8");
			BYTES_FRAME_ID_USER=STR_FRAME_ID_USER.getBytes("utf-8");
			BYTES_FRAME_ID_USLT=STR_FRAME_ID_USLT.getBytes("utf-8");
			BYTES_FRAME_ID_WCOM=STR_FRAME_ID_WCOM.getBytes("utf-8");
			BYTES_FRAME_ID_WCOP=STR_FRAME_ID_WCOP.getBytes("utf-8");
			BYTES_FRAME_ID_WOAF=STR_FRAME_ID_WOAF.getBytes("utf-8");
			BYTES_FRAME_ID_WOAR=STR_FRAME_ID_WOAR.getBytes("utf-8");
			BYTES_FRAME_ID_WOAS=STR_FRAME_ID_WOAS.getBytes("utf-8");
			BYTES_FRAME_ID_WORS=STR_FRAME_ID_WORS.getBytes("utf-8");
			BYTES_FRAME_ID_WPAY=STR_FRAME_ID_WPAY.getBytes("utf-8");
			BYTES_FRAME_ID_WPUB=STR_FRAME_ID_WPUB.getBytes("utf-8");
			BYTES_FRAME_ID_WXXX=STR_FRAME_ID_WXXX.getBytes("utf-8");

		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
}
